// lib/Di/di.dart
import 'package:connectivity_plus/connectivity_plus.dart'; // NEW: Import ConnectivityPlus
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'di.config.dart'; // This file is generated by build_runner

final getIt = GetIt.instance;

@injectableInit
Future<void> init() async {
  await getIt.init(); // this auto-registers using the generated code
}

// NEW: This module tells injectable how to provide an instance of Connectivity
@module
abstract class RegisterModule {
  // Use @lazySingleton to register a single instance that will be created
  // only when it's first requested.
  @lazySingleton
  Connectivity get connectivity => Connectivity();

// You would also typically register your PhotoRepository implementation here
// if it's not directly annotated with @injectable, @lazySingleton, etc.
// Example:
// @lazySingleton
// PhotoRepository get photoRepository => PhotoRepositoryImpl();
// (Assuming you have a PhotoRepositoryImpl class)
}